Permit attachment with different name using null char as separator
project-jedi/jvcl pull request #171
Opened 2023-11-08 19:55 UTC by did-vmonroig

As stated in documentation, https://wiki.delphi-jedi.org/wiki/JVCL_Help:TJvMail.Attachment:

> To send an attachment using a different file name, insert a null char (#0) between physical and virtual file names (ie: 'c:pathphysical name.ext'#0'virtualfilename.txt')

Nevertheless, this feature wasn't developed so this PR aims to do so.

2023-11-09 09:05 UTC, jfudickar commented
Can you add a documentation to the attachment property which describes this behaviour

2023-11-09 10:45 UTC, did-vmonroig commented
> Can you add a documentation to the attachment property which describes this behaviour

What I've done is develop a feature already documented in https://wiki.delphi-jedi.org/wiki/JVCL_Help:TJvMail.Attachment. Do you refer to another kind of documentation?

2023-11-09 11:26 UTC, jfudickar commented
I was not aware of this.
But still I would think that a comment in the code could be usefull.

2023-11-09 12:27 UTC, did-vmonroig commented
Added brief comments to new code.

2023-11-09 12:29 UTC, ronaldhoek requested changes

2023-11-09 12:29 UTC, ronaldhoek commented on jvcl/run/JvMail.pas
> +        // Look for #0 splitting parameter in physical filename (lpszPathName) and virtual name (lpszFileName)
Please remove `lpsz` prefix in `lpszPathName` and `lpszFileName` to the variable reference matches

2023-11-09 12:36 UTC, did-vmonroig commented
Done. `lpsz` prefix in comment was referring to the record TMapiFileDesc item name.

2023-11-11 22:51 UTC, jfudickar approved these changes

2023-11-11 22:52 UTC, merged